name: xeus
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - ninja
  - pkg-config
  # Host dependencies
  - nlohmann_json
  # Test dependencies
  - doctest >= 2.4.6
